added troubleshooting and IoT SIM section
EMnify/Documentation pull request #19
Opened 2021-09-02 14:56 UTC by ChristianHenkeEMnify

2021-09-02 15:56 UTC, kuberaspeaking requested changes

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +* click on Details -> events. Validate if there is any location update event created and rejected. The reasoning should indicate the resolution to fix the problem. If there is no location update even
```suggestion
* click on Details ->Events. Validate if there is any location update event created and rejected. The reasoning should indicate the resolution to the problem. If there is no location update event:
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +* ensure the device is powered on and searches for a network
```suggestion
* ensure that the device is powered on and searches for a network
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +* ensure that the APN is correctly set to 'em' or use alternatively 'emnify' as some devices do not support two digit APNs. Guides for different device can be found <<here, Getting the first device o
```suggestion
* ensure that the APN is correctly set to 'em' or alternatively 'emnify' as some devices do not support two letter APNs. Guides for different devices can be found <<Getting the first device online, here>>
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +* ensure mobile data is enabled, as well as international roaming is allowed
```suggestion
* ensure that mobile data is enabled, as well as international roaming is allowed 
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +* ensure mobile data is enabled, as well as international roaming is allowed
I think this is twice

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +* for NB-IoT and LTE-M this behaviour can happen when the device automatically connects to a network - rather specify the network that shall be used with using the `AT+COPS`. Also verify that the net
```suggestion
* for NB-IoT and LTE-M this behavior can happen when the device connects to a network automatically. In such a case, specify the network that is to be used with using the `AT+COPS` command. Also verify that the network is on EMnify's link:https://www.emnify.com/nb-iot-coverage[NB-IoT coverage] or 
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +* ensure that your data destination and DNS server (default EMnify uses googles 8.8.8.8 DNS if your device does not specify a DNS) is not blocked for the device
```suggestion
* ensure that your data destination and DNS server (by default EMnify uses googles 8.8.8.8 DNS if your device does not specify a DNS) is not blocked for the device
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +* after configuration changes make sure they are correctly applied on the device (e.g. with a reboot)
```suggestion
* after changing the configuration, make sure it is correctly applied to the device (e.g. with a reboot)
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +* a reset connectivity image:reset_connectivity.png[width=20] on Connected Devices can also reset the network state and allow your device to freshly reattach
```suggestion
* a reset connectivity image:reset_connectivity.png[width=20] on Connected Devices can also reset the network state and allow your device to reattach 
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +* the issue may only be present with one network or in the specific location (e.g. due to high interference for this network). You can use the Operator Blacklist to block the network and force the ch
```suggestion
* the issue may only be present with one network or at a specific location (e.g. due to high interference for this network). You can use the Operator Blacklist to block the network and force the SIM to change to a different network.   
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +IoT SIMs are more durable than regular SIM cards and come in different form factors and quality grades. EMnify has also a software application directly on the SIM so different operator profiles can b
```suggestion
IoT SIMs are more durable than regular SIM cards and come in different form factors and quality grades. EMnify also has a software application directly on the SIM so that different operator profiles can be used based on the location of the device. In this way EMnify can provide more networks than traditional operators. 
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +* 1FF (approximaltely size of a creditcard - only used in first GSM phone) - 85 x 54 x 0,76mm
```suggestion
* 1FF (approximaltely size of a creditcard - only used in first GSM phones) - 85 x 54 x 0,76mm 
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +EMnify offers pre-punched SIM cards in different combinations  2-in-1 (1FF and 2FF), 3-in-1 (1FF,2FF,3FF) and 4-in-1 (1FF,2FF,3FF,4FF). Especially in use cases where the devices are moving it is advi
```suggestion
EMnify offers pre-punched SIM cards in different combinations  2-in-1 (1FF and 2FF), 3-in-1 (1FF,2FF,3FF) and 4-in-1 (1FF,2FF,3FF,4FF). Especially in use cases where the devices constantly move, it is advisable to use a SIM which exactly fits the device and does not have another smaller form factor punched-out. That makes the SIMs  more durable and the contact with the device is firmer.  
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +Another form factor is MFF2 also called embedded SIM with the dimension 6 x 5 x 0.75-0.82mm. The embedded SIms are soldered onto a device and not removable.
```suggestion
Another form factor is MFF2 also called the embedded SIM with the dimensions 6 x 5 x 0.75-0.82mm. The embedded SIMs are soldered onto the device and are not removable. 
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +Note: Often the term eSIM is used for the MFF2 factor. Nevertheless the eSIM term is also used for SIMs whose operator profiles can be updated over the air. These eUICC based eSIM can be in any of th
```suggestion
Note: The term eSIM is often used for the MFF2 factor. Nevertheless the eSIM term is also used for SIMs whose operator profiles can be updated over the air. These eUICC based eSIM can be in any of the described form factors - not only in MFF2. While eSIM/eUICC is widely adopted for consumer smartphone and watches, for IoT use cases (where the profile cannot be download via a screen or QR reader) the commercial and deployment model of the required infrastructure prohibits an easy change of operator profiles and is therefore not widely adopted.    
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +The EMnify SIM cards come in two different quality grades Commercial and Industrial. In below table a comparison to a standard consumer SIM is made.
```suggestion
The EMnify SIM cards come in two different quality grades - Commercial and Industrial. The table shows a comparison with a standard consumer SIM.  
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +EMnify offers an easy entry to test the services and platform by downloading an EMnify eSIM profile to an eSIM capable phone or tablet. During the trial period every organisation has the option to do
```suggestion
EMnify offers an easy entry to test the services and platform by downloading an EMnify eSIM profile to an eSIM compatible phone or tablet. During the trial period every organization has the option to download one profile which can be used instantly. 
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +The eSIM does not use a multi-IMSI applet (as on the physical SIM cards) and therefore has some difference in the network coverage. For a list of supported devices and limitations please refer to the
```suggestion
The eSIM does not use a multi-IMSI applet (as on the physical SIM cards) and therefore has some differences in the network coverage. For a list of supported devices and limitations please refer to the link:https://support.emnify.com/hc/en-us/articles/360021545600-Evaluation-eSIM-device-support-and-restrictions#h_01F7V2BVKT0RQRVXK3VNSPYQMW[knowledge base] 
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +The eSIM can be used to test and verify all EMnify functionality including:
```suggestion
The eSIM can be used to test and verify all EMnify functionalities including:
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +* Cloud Connect and Datastreamer integration
```suggestion
* Cloud Connect and Multi Cloud Data Streamer integration
```

2021-09-02 15:56 UTC, kuberaspeaking commented on README.adoc
> +* Zapier
```suggestion
* Zapier- No-Code Integrations
```

2021-09-03 10:19 UTC, ChristianHenkeEMnify commented on README.adoc
> +* Cloud Connect and Datastreamer integration
> 

Would not call it multi cloud data streamer.

2021-09-03 10:20 UTC, kuberaspeaking approved these changes

2021-09-03 10:20 UTC, merged